### PR TITLE
Started a notebook to run model train/predict code

### PR DESCRIPTION
**Pull request by minshenhao1**

### CODE REVIEW

**Comment by minshenhao1** [comment]
We will need to modify the hard coded directory paths in order to run the model code. 

After setting all paths right, we then need to run scripts in `./dataprocess/`.

Two libraries installed:

pip install opencv-python==3.3.0.10 
pip install SimpleITK

**Comment by minshenhao1** [comment]
@neo-cc @LucRyan FYI.

**Comment by LucRyan** [comment]
还有我已经把所有的path都搞定了，但是改了一些名字，比如说log 改成了model/trained.
大哥看一下develop里面新的改动。

**Comment by LucRyan** [comment]
test me

**Comment by neo-cc** [comment]
I was able to run Nodule Detection prediction (vnet3d_predict.py). 

Image 6-14-19 at 12 36 AM

**Pull request merged**
